---
- name: Stop and backup database changes
  hosts: localhost
  become: yes
  tasks:

    - name: Generate migration for new data
      ansible.builtin.shell: |
        # Dump the new data changes into a migration file with timestamp
        mysqldump -u root -prootpassword --no-create-info subscribers > migrations/V$(date +%Y%m%d%H%M%S)__new_data.sql

    - name: Stop MySQL
      ansible.builtin.service:
        name: mysql
        state: stopped  # Stop MySQL service after backup
