---
- name: Stop and backup database changes
  hosts: localhost
  become: yes
  tasks:

  - name: Generate migration for new data
    ansible.builtin.shell: |
      mysqldump -u root -prootpassword --no-create-info subscribers > migrations/V$(date +%Y%m%d%H%M%S)__new_data.sql

  - name: Stop MySQL
    ansible.builtin.service:
      name: mysql
      state: stopped
