---
- name: Start and maintain database
  hosts: localhost
  become: yes
  vars:
    migrations_dir: "{{ playbook_dir }}/migrations"  # Define migrations directory using playbook directory

  tasks:
    - name: Start MySQL
      ansible.builtin.service:
        name: mysql
        state: started  # Ensure MySQL service is running

    - name: Ensure Flyway is installed
      ansible.builtin.shell: |
        if ! command -v flyway &> /dev/null; then
          # Download and install Flyway if not already installed
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.0.0/flyway-commandline-9.0.0-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          mv flyway-9.0.0 /opt/flyway
          ln -s /opt/flyway/flyway /usr/local/bin/flyway
        fi
      args:
        creates: /usr/local/bin/flyway  # Skip this task if Flyway is already installed

    - name: Run Flyway migrations
      ansible.builtin.shell: flyway -url=jdbc:mysql://127.0.0.1:3306/subscribers -user=flyway -password=flywaypassword -locations=filesystem:{{ migrations_dir }} migrate
      # Execute Flyway migrations using the migrations directory defined as a variable

    - name: Run schema validation tests
      ansible.builtin.shell: python3 dbtests.py  # Run the schema validation script to ensure the database schema is correct
